#!/bin/bash
cd $1
for i in *
do
    titre=$(echo `../../../MP3INFO "$i"` | cut -f3 -d ":")
    numero=$(echo `../../../MP3INFO "$i"` | cut -f6 -d ":")
    echo $numero"-"$titre
done | sort -n | cut -f2 -d "-"
